<?xml version = "1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE document [
<!ELEMENT document (employee)*>
<!ELEMENT employee (intern?, name, hiredate, projects)>
<!ELEMENT name (lastname, firstname)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT hiredate (#PCDATA)>
<!ELEMENT projects (project)*>
<!ELEMENT project (product, id, price)>
<!ELEMENT product (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT intern EMPTY>
]>
<document>
    <employee>
    <intern/>
        <name>
               <firstname>Nguyen</firstname>
	<lastname>Son Nam</lastname>
        </name>
        <hiredate>July 15, 2005</hiredate>
        <projects>
            <project>
                <product>Printer</product>
                <id>HP2300</id>
                <price>$111.00</price>
            </project>
            <project>
                <product>Laptop</product>
                <id>DELL1100</id>
                <price>$989.00</price>
            </project>
        </projects>
    </employee>
. . .
</document>