=== mymoon89/SPKT_TRANTHITHUY/GiaoTrinh/DacTaHinhThuc/OntapDTHT/08110/Nhom 03/ORDERS.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ENTER_NAME_OF_ROOT_ELEMENT_HERE EMPTY>
<!ELEMENT DOCUMENT (CUSTOMER)*>
<!ELEMENT CUSTOMER (NAME,DATE,ORDERS)>
<!ELEMENT NAME (LAST_NAME,FIRST_NAME)>
<!ELEMENT LAST_NAME (#PCDATA)>
<!ELEMENT FIRST_NAME (#PCDATA)>
<!ELEMENT DATE (#PCDATA)>
<!ELEMENT ORDERS (ITEM)*>
<!ELEMENT ITEM (PRODUCT,NUMBER,PRICE)>
<!ELEMENT PRODUCT (#PCDATA)>
<!ELEMENT NUMBER (#PCDATA)>
<!ELEMENT PRICE (#PCDATA)>

=== mymoon89/SPKT_TRANTHITHUY/GiaoTrinh/DacTaHinhThuc/OntapDTHT/08110/Nhom 03/vidu5.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE DOCUMENT SYSTEM "ORDERS.dtd">
<DOCUMENT>
<CUSTOMER>
	<NAME>
		<LAST_NAME>Jacky</LAST_NAME>
		<FIRST_NAME>Chan</FIRST_NAME>
	</NAME>
	<DATE>12/11/2020</DATE>
	<ORDERS>
		<ITEM>
			<PRODUCT>Books</PRODUCT>
			<NUMBER>2</NUMBER>
			<PRICE>$2</PRICE>
		</ITEM>
	</ORDERS>
</CUSTOMER>
</DOCUMENT>
