<?xml version="1.0" standalone="yes"?>
<!-- edited with XMLSpy v2008 rel. 2 sp2 (http://www.altova.com) by mazuki (darksiderg) -->
<!DOCTYPE DOCUMENT [
	<!ELEMENT DOCUMENT (CUSTOMER)*>
	<!ELEMENT CUSTOMER (NAME, DATE, ORDERS+, SEX?)>
	<!ELEMENT NAME (LAST_NAME, FIRST_NAME)>
	<!ELEMENT LAST_NAME (#PCDATA)>
	<!ELEMENT FIRST_NAME (#PCDATA)>
	<!ELEMENT DATE (#PCDATA)>
	<!ELEMENT ORDERS (ITEM)*>
	<!ELEMENT ITEM (PRODUCT, NUMBER, PRICE)>
	<!ELEMENT PRODUCT (#PCDATA)>
	<!ELEMENT NUMBER (#PCDATA)>
	<!ELEMENT PRICE (#PCDATA)>
	<!ELEMENT SEX (#PCDATA)>
]>
<DOCUMENT>
	<CUSTOMER>
		<NAME>
			<LAST_NAME>Jonny</LAST_NAME>
			<FIRST_NAME>Tom</FIRST_NAME>
		</NAME>
		<DATE>october,11,1988</DATE>
		<ORDERS>
			<ITEM>
				<PRODUCT>TV</PRODUCT>
				<NUMBER>2</NUMBER>
				<PRICE>$123</PRICE>
			</ITEM>
		</ORDERS>
		<SEX>MALE</SEX>
	</CUSTOMER>
	<CUSTOMER>
		<NAME>
			<LAST_NAME>MESSI</LAST_NAME>
			<FIRST_NAME>Lionel</FIRST_NAME>
		</NAME>
		<DATE>June, 24, 1987</DATE>
		<ORDERS>
		<ITEM>
			<PRODUCT>Shoes</PRODUCT>
			<NUMBER>2</NUMBER>
			<PRICE>$25</PRICE>
		</ITEM>
		</ORDERS>
		<SEX>MALE</SEX>
	</CUSTOMER>
</DOCUMENT>
