=== mymoon89/SPKT_TRANTHITHUY/GiaoTrinh/DacTaHinhThuc/OntapDTHT/08110/Nhom 05/TrungDemo/Baseball_Statistics.dtd
<!ELEMENT SEASON (LEAGUE, LEAGUE)>
<!ELEMENT LEAGUE (DIVISION, DIVISION, DIVISION)>
<!ELEMENT DIVISION (TEAM+)>
<!ELEMENT TEAM (PLAYER*)>
<!ELEMENT PLAYER EMPTY>
<!ATTLIST SEASON YEAR CDATA #REQUIRED>
<!ATTLIST LEAGUE NAME CDATA #REQUIRED>
<!ATTLIST DIVISION NAME CDATA #REQUIRED>
<!ATTLIST TEAM NAME CDATA #REQUIRED
								CITY CDATA #REQUIRED>
<!ATTLIST PLAYER GIVEN_NAME CDATA #REQUIRED>
<!ATTLIST PLAYER SURNAME CDATA #REQUIRED>
<!ATTLIST PLAYER POSITION CDATA #REQUIRED>
<!ATTLIST PLAYER GAMES CDATA #REQUIRED>
<!ATTLIST PLAYER GAMES_STARTED CDATA #REQUIRED>
<!-- Batting Statistics -->
<!ATTLIST PLAYER AT_BATS CDATA #IMPLIED>
<!ATTLIST PLAYER RUNS CDATA #IMPLIED>
<!ATTLIST PLAYER HITS CDATA #IMPLIED>
<!ATTLIST PLAYER DOUBLES CDATA #IMPLIED>
<!ATTLIST PLAYER TRIPLES CDATA #IMPLIED>
<!ATTLIST PLAYER HOME_RUNS CDATA #IMPLIED>
<!ATTLIST PLAYER RBI CDATA #IMPLIED>
<!ATTLIST PLAYER STEALS CDATA #IMPLIED>
<!ATTLIST PLAYER CAUGHT_STEALING CDATA #IMPLIED>
<!ATTLIST PLAYER SACRIFICE_HITS CDATA #IMPLIED>
<!ATTLIST PLAYER SACRIFICE_FLIES CDATA #IMPLIED>
<!ATTLIST PLAYER ERRORS CDATA #IMPLIED>
<!ATTLIST PLAYER WALKS CDATA #IMPLIED>
<!ATTLIST PLAYER STRUCK_OUT CDATA #IMPLIED>
<!ATTLIST PLAYER HIT_BY_PITCH CDATA #IMPLIED>
<!-- Pitching Statistics -->
<!ATTLIST PLAYER WINS CDATA #IMPLIED>
<!ATTLIST PLAYER LOSSES CDATA #IMPLIED>
<!ATTLIST PLAYER SAVES CDATA #IMPLIED>
<!ATTLIST PLAYER COMPLETE_GAMES CDATA #IMPLIED>
<!ATTLIST PLAYER SHUTOUTS CDATA #IMPLIED>
<!ATTLIST PLAYER ERA CDATA #IMPLIED>
<!ATTLIST PLAYER INNINGS CDATA #IMPLIED>
<!ATTLIST PLAYER HOME_RUNS_AGAINST CDATA #IMPLIED>
<!ATTLIST PLAYER RUNS_AGAINST CDATA #IMPLIED>
<!ATTLIST PLAYER EARNED_RUNS CDATA #IMPLIED>
<!ATTLIST PLAYER HIT_BATTER CDATA #IMPLIED>
<!ATTLIST PLAYER WILD_PITCHES CDATA #IMPLIED>
<!ATTLIST PLAYER BALK CDATA #IMPLIED>
<!ATTLIST PLAYER WALKED_BATTER CDATA #IMPLIED>
<!ATTLIST PLAYER STRUCK_OUT_BATTER CDATA #IMPLIED>

=== mymoon89/SPKT_TRANTHITHUY/GiaoTrinh/DacTaHinhThuc/OntapDTHT/08110/Nhom 05/TrungDemo/Baseball_Statistics.xml
<?xml version="1.0" standalone="yes"?>
<!DOCTYPE SEASON SYSTEM "Baseball_Statistics.dtd">
<SEASON YEAR="1998">
	<LEAGUE NAME="National League">
		<DIVISION NAME="East">
			<TEAM CITY="Atlanta" NAME="Braves">
				<PLAYER GIVEN_NAME="Marty" SURNAME="Malloy" POSITION="”Second Base" GAMES="11" GAMES_STARTED="8" AT_BATS="28" RUNS="3" HITS="5" DOUBLES="1" TRIPLES="0" HOME_RUNS="1" RBI="1" STEALS="0" CAUGHT_STEALING="0" SACRIFICE_HITS="0" SACRIFICE_FLIES="0" ERRORS="0" WALKS="2" STRUCK_OUT="2" HIT_BY_PITCH="0"/>
				<PLAYER GIVEN_NAME="Tom" SURNAME="Glavine" POSITION="”Starting Pitcher" GAMES="33" GAMES_STARTED="33" WINS="20" LOSSES="6" SAVES="0" COMPLETE_GAMES="4" SHUTOUTS="3" ERA="2.47" INNINGS="229.1" HOME_RUNS_AGAINST="13" RUNS_AGAINST="67" EARNED_RUNS="63" HIT_BATTER="2" WILD_PITCHES="3" BALK="0" WALKED_BATTER="74" STRUCK_OUT_BATTER="157"/>
			</TEAM>
		</DIVISION>
		<DIVISION NAME="Central">
			<TEAM CITY="Chicago" NAME="Cubs">
			</TEAM>
		</DIVISION>
		<DIVISION NAME="West">
			<TEAM CITY="San Francisco" NAME="Giants">
			</TEAM>
		</DIVISION>
	</LEAGUE>
	<LEAGUE NAME="American League">
		<DIVISION NAME="East">
			<TEAM CITY="New York" NAME="Yankees">
			</TEAM>
		</DIVISION>
		<DIVISION NAME="Central">
			<TEAM CITY="Minnesota" NAME="Twins">
			</TEAM>
		</DIVISION>
		<DIVISION NAME="West">
			<TEAM CITY="Oakland" NAME="Athletics">
			</TEAM>
		</DIVISION>
	</LEAGUE>
</SEASON>
