<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="data.css"?>
<!DOCTYPE PROJECTDB[
<!ELEMENT PROJECTDB ANY>
<!ELEMENT TOPICAREA   ANY>
<!ELEMENT PROJECT ANY>
<!ELEMENT PROJECTTITLE  ANY>
<!ELEMENT DEVELOPER ANY>
<!ELEMENT CONTACT ANY>
]>
<PROJECTDB>
  <TOPICAREA>
      <PROJECT>
        <PROJECTTITLE>title</PROJECTTITLE>
        <PROJECTTITLE>PROJECTTITLE DISPLAY BLOCK</PROJECTTITLE>
        <DEVELOPER>developer</DEVELOPER>
        <DEVELOPER>DEVELOPER DISPLAY BLOCK CONTENT TEXT</DEVELOPER>
        <CONTACT>address</CONTACT>
      </PROJECT>
  </TOPICAREA>
</PROJECTDB>