<?xml version="1.0" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="vd2.xsl"?>
<!DOCTYPE PERSON [
	<!ELEMENT PERSON (NAME, EMPLOYEE_ID, PHONE, OFFICE)>
	<!ELEMENT NAME (#PCDATA)>
	<!ELEMENT EMPLOYEE_ID (#PCDATA)>
	<!ELEMENT PHONE (#PCDATA)>
	<!ELEMENT OFFICE (#PCDATA)>
	<!NOTATION JPEG SYSTEM "image/jpg">
	<!ENTITY ROGER SYSTEM "rogers.jpg" NDATA JPEG>
	<!ATTLIST PERSON PHOTO ENTITY #REQUIRED>
]>
<PERSON PHOTO="ROGER">
	<NAME>Jim Rogers</NAME>
	<EMPLOYEE_ID>4534</EMPLOYEE_ID>
	<PHONE>X396</PHONE>
	<OFFICE>RH 415A</OFFICE>
</PERSON>
