=== mymoon89/SPKT_TRANTHITHUY/GiaoTrinh/DacTaHinhThuc/OntapDTHT/08110/Nhom 07/Bao cao DTHT/xml/Chuong5/Ch5/vidu5-11.dtd
<?xml version = "1.0" encoding="UTF-8"?>
<!ENTITY % record "(date, text)">
<!ELEMENT document (employee)*>
<!ELEMENT employee (name, hiredate, projects,
supervisorComment*, customerComment*,
employeeComment*)>
<!ELEMENT name (lastname, firstname)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT hiredate (#PCDATA)>
<!ELEMENT projects (project)*>
<!ELEMENT supervisorComment %record;>
<!ELEMENT customerComment %record;>
<!ELEMENT employeeComment %record;>
<!ELEMENT project (product, id, price)>
<!ELEMENT product (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ATTLIST employee supervisor CDATA #IMPLIED>

=== mymoon89/SPKT_TRANTHITHUY/GiaoTrinh/DacTaHinhThuc/OntapDTHT/08110/Nhom 07/Bao cao DTHT/xml/Chuong5/Ch5/vidu5-11.xml
<?xml version = "1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE document SYSTEM "vidu5-11.dtd">
<document>
<employee supervisor="no">
<copy>&copyright;</copy>
        <name>
               <firstname>Nguyen</firstname>
	<lastname>Son Nam</lastname>
        </name>
<hiredate>July 15, 2005</hiredate>
        <projects>
            <project>
                <product>Printer</product>
                <id>HP2300</id>
                <price>$111.00</price>
            </project>
            <project>
                <product>Laptop</product>
                <id>DELL1100</id>
                <price>$989.00</price>
            </project>
        </projects>
    </employee>
<employee supervisor="no">
<copy>&copyright;</copy>
        <name>
	<firstname>Le Thi</firstname>
	<lastname>Kieu Oanh</lastname>
        </name>
        <hiredate>October 20, 2005</hiredate>
        <projects>
            <project>
                <product>Desktop</product>
                <id>LV333</id>
                <price>$595.00</price>
            </project>
            <project>
                <product>Scanner</product>
                <id>CANON444</id>
                <price>$200.00</price>
            </project>
        </projects>
    </employee>
</document>
